### ISSUE TITLE
JavaScript DrumKit

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#1]

**Comment by RiyaGupta89** [comment]
Can I work on it sir? Can I add javascript drumkit? Please assign me this issue.

**Comment by Ayushparikh-code** [comment]
ok assigned you

**Comment by RiyaGupta89** [comment]
Why is .gitkeep file used? Is it only used when the folders are empty or some other purpose it has? @Ayushparikh-code

**Comment by Ayushparikh-code** [comment]
> Why is the .gitkeep file used? Is it only used when the folders are empty or for some other purpose it has? @Ayushparikh-code

yeah u can delete it, I used it to push empty project folders from my local to this remote repository because git can't track empty folders, so ignore that file !
