### ISSUE TITLE
Speed Distance Time Calculator 

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#105]

**Comment by jugeshraghav** [comment]
I want to work on this issue.

**Comment by joshi-kaushal** [comment]
Is this still on? I can work on this

**Comment by RiyaGupta89** [comment]
Hey, its been too long. Can I work on this issue? @jugeshraghav  might be busy.

**Comment by jugeshraghav** [comment]
@RiyaGupta89  i am working on this issue, ya i am a little late but i have almost completed it i will create a PR today
