### ISSUE TITLE
Youtube Clone

### ISSUE THREAD

**Issue by mrkc2303** [Ayushparikh-code/Web-dev-mini-projects#11]
I would like to add a mini project on cloning youtube UI. I would make it as responsive as possible using pure HTML & CSS. 
After learning HTML, CSS, and JS, I decided to make a clone of youtube UI to practice and enhance my skills. I am still working on this project and will add it when it is fully completed. 
Please assign me this issue under LGMSOC'21 so that I can start working on it.

**Comment by Ayushparikh-code** [comment]
> I would like to add a mini project on cloning youtube UI. I would make it as responsive as possible using pure HTML & CSS.
> After learning HTML, CSS, and JS, I decided to make a clone of youtube UI to practice and enhance my skills. I am still working on this project and will add it when it is fully completed.
> Please assign me this issue under LGMSOC'21 so that I can start working on it.

ok sure will assign u for it but first, create a pull request for your previous assigned issue!

**Comment by mrkc2303** [comment]
Added a PR for the previous Issue!

**Comment by Ayushparikh-code** [comment]
> I would like to add a mini project on cloning youtube UI. I would make it as responsive as possible using pure HTML & CSS.
> After learning HTML, CSS, and JS, I decided to make a clone of youtube UI to practice and enhance my skills. I am still working on this project and will add it when it is fully completed.
> Please assign me this issue under LGMSOC'21 so that I can start working on it.

Also add a README file to your project which consists the short description/screenshots about your project !

**Comment by mrkc2303** [comment]
Sure!
It will take me 2-3 more days to fully complete this project.

**Comment by Ayushparikh-code** [comment]
> Sure!
> It will take me 2-3 more days to fully complete this project.

no worries take your time ✌️
