### ISSUE TITLE
Bmi calculator in js

### ISSUE THREAD

**Issue by siddhi-244** [Ayushparikh-code/Web-dev-mini-projects#126]
It is basically a bmi calculator using javascript.
There will be 2 inputs for weight and height and then after clicking on button the bmi will be calculated
It can be used in various gyms.
Plzz assign me this under lgmsoc

**Comment by chicken-biryani** [comment]
@siddhi-244 Kindly describe the issue a little more.

**Comment by siddhi-244** [comment]
@chicken-biryani Done!
