### ISSUE TITLE
Temperature Convertor

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#138]
I would like to add a temperature convertor.
I would like to work on this issue. @Ayushparikh-code

**Comment by chicken-biryani** [comment]
Could you describe the project a little more?

**Comment by joshi-kaushal** [comment]
I am interested to solve this issue...

**Comment by chicken-biryani** [comment]
@joshi-kaushal it has already been assigned. Maybe you can work on another issue?

**Comment by harshita2216** [comment]
This issue has been inactive for 9 days with no updates. I am assigning this issue to @joshi-kaushal.

**Comment by harshita2216** [comment]
@jugeshraghav #139 is also inactive for 9 days. Although, I haven't unassigned you. 
Please keep us updated on your progress.
