### ISSUE TITLE
Random Color Generator (rgb color)

### ISSUE THREAD

**Issue by yellowberard** [Ayushparikh-code/Web-dev-mini-projects#14]
I would like to add a mini project in which a random color s generated and it's rgb value is given. I have started my started my web development journey last month and made a small project.

Please assign me this issue under LGMSOC'21 so that I can start working on it.

**Comment by Ayushparikh-code** [comment]
> I would like to add a mini project in which a random color s generated and it's rgb value is given. I have started my started my web development journey last month and made a small project.
> 
> Please assign me this issue under LGMSOC'21 so that I can start working on it.

ok assigned you ✔️👍
