### ISSUE TITLE
A static Band website .

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#140]
I would like to work on this issue. @Ayushparikh-code

**Comment by chicken-biryani** [comment]
@jugeshraghav Could you please describe the project a little more?

**Comment by harshita2216** [comment]
@jugeshraghav Would be assigned when you're done with the other two assigned issues.

**Comment by jugeshraghav** [comment]
Okay I will elaborate it.

**Comment by jugeshraghav** [comment]
Please assign it to me @harshita2216

**Comment by jugeshraghav** [comment]
I will create a static multi page website for this.
