### ISSUE TITLE
Playing with color of buttons

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#144]
![challenge1](https://user-images.githubusercontent.com/72425181/124771920-2d4c7180-df59-11eb-8b6a-1f91f308d440.png)
Can I add this project where a user plays with the color of the buttons. We can a few option for the user to select from. A user selects an option and all the buttons changes to that particular color. This is a good beginner friendly project where a user will get to know about a lot of new things.
![challenge2](https://user-images.githubusercontent.com/72425181/124771933-2faecb80-df59-11eb-94a0-af152a6fd099.png)

**Comment by harshita2216** [comment]
Would assign this to you once you're done with the other two. @RiyaGupta89

**Comment by harshita2216** [comment]
You can go ahead with this one now, @RiyaGupta89

**Comment by RiyaGupta89** [comment]
Done. Please review the PR :)
