### ISSUE TITLE
Survery form

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#145]
![survey](https://user-images.githubusercontent.com/72425181/124773613-badc9100-df5a-11eb-9a3e-00e6f1ac095c.png)
Can I add this survey form?
Also please tell me if only html, css, js is allowed in this project? Or we can also use nodejs in our projects?

**Comment by harshita2216** [comment]
Yes, you can. @RiyaGupta89 
Anything that falls under Web Development can be used.
