### ISSUE TITLE
Live Clock using React Native

### ISSUE THREAD

**Issue by palaksinghania05** [Ayushparikh-code/Web-dev-mini-projects#150]
This project will show live clock timing on the web page.

**Comment by palaksinghania05** [comment]
@harshita2216  could you please assign me this issue?

**Comment by harshita2216** [comment]
Hey @palaksinghania05, please don't create PRs until you've been assigned the issue. Thanks!

**Comment by chicken-biryani** [comment]
@palaksinghania05 
 1)Don't work on an issue until and unless it has not been assigned to you.
 2) Please describe a description of your project. 
 
I am closing the PR, Please re-do it, as now it has been assigned to u.

**Comment by palaksinghania05** [comment]
Hey @harshita2216 and @chicken-biryani , that PR was for another issue which was assigned to me i.e., adding weight converter. Sonce I had submitted the PR for that issue so I opened a new issue.
Please let me know why you closed that PR?
Thanks!

**Comment by harshita2216** [comment]
@palaksinghania05, don't worry. We have reopened it. There was a small confusion. You can continue with working on this one. Cheers! 🥂

**Comment by chicken-biryani** [comment]
@palaksinghania05 Ahh! My bad! Please refer to the correct issue, from next time. 

I thought the issue was unassigned and you were working on it, thus I closed it!
