### ISSUE TITLE
Add Image Filter App

### ISSUE THREAD

**Issue by Atif0604** [Ayushparikh-code/Web-dev-mini-projects#153]
**Project title**
Image Filter App

Stack:
[✔️ ] Html
[✔️ ] CSS
[✔️ ] JavaScript

**Comment by Ayushparikh-code** [comment]
> **Project title**
> Image Filter App
> 
> Stack:
> [✔️ ] Html
> [✔️ ] CSS
> [✔️ ] JavaScript



> **Project title**
> Image Filter App
> 
> Stack:
> [✔️ ] Html
> [✔️ ] CSS
> [✔️ ] JavaScript

ok you're assigned for it but do add project description also when raising issue

**Comment by Atif0604** [comment]
> > **Project title**
> > Image Filter App
> > Stack:
> > [✔️ ] Html
> > [✔️ ] CSS
> > [✔️ ] JavaScript
> 
> > **Project title**
> > Image Filter App
> > Stack:
> > [✔️ ] Html
> > [✔️ ] CSS
> > [✔️ ] JavaScript
> 
> ok you're assigned for it but do add project description also when raising issue

I would a App in which you can upload the image and apply diff effects or increase decrease saturation/brightness and all
