### ISSUE TITLE
Tip Calculator

### ISSUE THREAD

**Issue by supzi-del** [Ayushparikh-code/Web-dev-mini-projects#156]
**Project title**
Tip Calculator

**Project Description**
This script consists of user input--> total bill amount and bill percent and it calculates the tip amount and the total bill.

Stack:
[x] Html
[x] CSS
[x] JavaScript

**Comment by supzi-del** [comment]
Please assign it to me! :)

**Comment by supzi-del** [comment]
Hey! Can this issue be closed after merging PR?

**Comment by Ayushparikh-code** [comment]
> Hey! Can this issue be closed after merging PR?

yeah
