### ISSUE TITLE
Jump Game 

### ISSUE THREAD

**Issue by rajbir21-droid** [Ayushparikh-code/Web-dev-mini-projects#16]
I would like to add a mini project a jump game . It is a simple game similar to the one present in chrome when someone is offline
Please assign me this issue under LGMSOC'21 so that I can start working on it.

**Comment by Ayushparikh-code** [comment]
> I would like to add a mini project a jump game . It is a simple game similar to the one present in chrome when someone is offline
> Please assign me this issue under LGMSOC'21 so that I can start working on it.

assigned you ✔️👍
