### ISSUE TITLE
Add a glassmorphism form

### ISSUE THREAD

**Issue by siddhi-244** [Ayushparikh-code/Web-dev-mini-projects#163]
**Project title**
Add a glassmorphism form

**Project Description**
It will be a glassmorphism animation login page.

Stack:
[x] Html
[x] CSS
[] JavaScript

**Comment by nandini040** [comment]
Hey @chicken-biryani  Can you assign this issue to me I would like to work on this issue.

**Comment by siddhi-244** [comment]
> Hey @chicken-biryani Can you assign this issue to me I would like to work on this issue.

I have asked for this issue!

**Comment by chicken-biryani** [comment]
Hey @nandini040 since, @siddhi-244 has created the issue it would be better to assign it to her. But i am sure you can create an issue of your own and work on that.
