### ISSUE TITLE
Connect Four Mini JS Game 

### ISSUE THREAD

**Issue by Shauryaditya** [Ayushparikh-code/Web-dev-mini-projects#17]
This is a Javascript game  which can be played between two players . Players have to connect  bubbles . The player who connects four bubble first wins the game . Bubbles could be matched horizontally , vertically and diagonally. Please assign me this issue under LGMSOC'21 so that I can start working on it.

**Comment by Ayushparikh-code** [comment]
done✔️assigned u for this !👍

**Comment by Ayushparikh-code** [comment]
> This is a Javascript game which can be played between two players . Players have to connect bubbles . The player who connects four bubble first wins the game . Bubbles could be matched horizontally , vertically and diagonally. Please assign me this issue under LGMSOC'21 so that I can start working on it.

Also add a README file to your project which consists the short description/screenshots about your project !
