### ISSUE TITLE
Beginner friendly javascript infinite rainbow

### ISSUE THREAD

**Issue by girija0707** [Ayushparikh-code/Web-dev-mini-projects#171]
**Project title**
Beginner friendly javascript infinite rainbow

**Project Description**
Being able to make static pages look more appealing with graphical elements 

Stack:
[ ] Html
[ ] CSS
[ ] JavaScript

**Comment by girija0707** [comment]
please assign this

**Comment by harshita2216** [comment]
@girija0707 Updates?

**Comment by harshita2216** [comment]
Inactive issue, hence will have to close it. You may open this again when you're ready to work on this. 
Thanks.

**Comment by girija0707** [comment]
Sorry I wasn't keeping well,but now I'm ready to work on the issue

**Comment by harshita2216** [comment]
Go ahead! 🚀 @girija0707

**Comment by harshita2216** [comment]
@girija0707 updates?

**Comment by harshita2216** [comment]
> Inactive issue, hence will have to close it. You may open this again when you're ready to work on this.
> Thanks.

⬆️
