### ISSUE TITLE
BMI Calculator (Flask)

### ISSUE THREAD

**Issue by tanvi355** [Ayushparikh-code/Web-dev-mini-projects#184]
**BMI Calculator using Flask**

**Project Description**
A simple BMI calculator made using the Flask framework.

Stack:
[x] HTML
[x] CSS
[x] Python
[x] Flask

**Comment by tanvi355** [comment]
I would like to work on this.

**Comment by Ayushparikh-code** [comment]
> I would like to work on this.

Sure
