### ISSUE TITLE
Basic Contact Form

### ISSUE THREAD

**Issue by sonamgupta136** [Ayushparikh-code/Web-dev-mini-projects#185]
**Project title**
Contact Form

**Project Description**
It is a basic contact form having send and reset button

Stack:
[x] Html
[x] CSS
[x] JavaScript

**Comment by sonamgupta136** [comment]
kindly assign me @chicken-biryani

**Comment by swathi-469** [comment]
Can I work on this issue please assign this to me

**Comment by chicken-biryani** [comment]
Hey @swathi-469 , the issue has already been assigned to @sonamgupta136 ! But you can always make an issue about another project and work on that.

Also never start working on an issue until and unless it has not been assigned to you.
