### ISSUE TITLE
Breaking Bad Characters

### ISSUE THREAD

**Issue by khushi-purwar** [Ayushparikh-code/Web-dev-mini-projects#186]
**Project title**
Breaking Bad Characters

**Project Description**
It is a React project that uses the breaking bad API to show and filter characters from the show

Stack:
- [x] React
- [x] JavaScript

**Comment by khushi-purwar** [comment]
Hey @chicken-biryani can I work on this project?

**Comment by harshita2216** [comment]
@khushi-purwar, can you describe some other  features of the website also, just curious? 🙈

**Comment by khushi-purwar** [comment]
> @khushi-purwar, can you describe some other features of the website also, just curious? 🙈

Breaking Bad is an American series and it is produced by Vinci Gilligan. An API is available to get all the information about the characters, episodes of the series, i.e Breaking Bad API (https://www.breakingbadapi.com/api/)

The main motive of this project is,  how we can play with the API and can integrate API in the websites.

Hope you will like my project and the project idea @harshita2216

**Comment by harshita2216** [comment]
> > @khushi-purwar, can you describe some other features of the website also, just curious? 🙈
> 
> Breaking Bad is an American series and it is produced by Vinci Gilligan. An API is available to get all the information about the characters, episodes of the series, i.e Breaking Bad API (https://www.breakingbadapi.com/api/)
> 
> The main motive of this project is, how we can play with the API and can integrate API in the websites.
> 
> Hope you will like my project and the project idea @harshita2216

Hey I know that! 😅 I meant apart from displaying the characters, what other features would you be providing?

**Comment by khushi-purwar** [comment]
> > > @khushi-purwar, can you describe some other features of the website also, just curious? 🙈
> > 
> > 
> > Breaking Bad is an American series and it is produced by Vinci Gilligan. An API is available to get all the information about the characters, episodes of the series, i.e Breaking Bad API (https://www.breakingbadapi.com/api/)
> > The main motive of this project is, how we can play with the API and can integrate API in the websites.
> > Hope you will like my project and the project idea @harshita2216
> 
> Hey I know that! 😅 I meant apart from displaying the characters, what other features would you be providing?

Oh ok 😊. I will be displaying the characters.
