### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by ayushseth07** [Ayushparikh-code/Web-dev-mini-projects#196]
**Project title**
Todolist

**Project Description**
Todolist built using node.js

Stack:
[x] Html
[x] CSS
[x] JavaScript

**Comment by harshita2216** [comment]
@ayushseth07, always add relevant titles, please!

**Comment by joshi-kaushal** [comment]
I can work on this if needed

**Comment by ayushseth07** [comment]
@joshi-kaushal needless. I have done the work just some final touches remaining :)
