### ISSUE TITLE
calculator

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#2]

**Comment by Ciggzy1312** [comment]
I would like to work on this issue as a LGMSOC participant

**Comment by Ayushparikh-code** [comment]
> I would like to work on this issue as an LGMSOC participant

ok, I assigned you for this so start working ! after merging you or for this issue will assign you for the next issue !

**Comment by palaksinghania05** [comment]
I also want to work on this issue.
