### ISSUE TITLE
Add the appropriate license in the README

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#203]
**Project name**
(--)

**Project link**
(--)

**Improvements suggested**
Add the appropriate license In the README. Use https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository to learn about licenses.

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by harshita2216** [comment]
@ujju20 updates?

**Comment by ujju20** [comment]
I have made the PR. Check it.
