### ISSUE TITLE
Tindog

### ISSUE THREAD

**Issue by gunjan-g** [Ayushparikh-code/Web-dev-mini-projects#209]
**Project title**
Tindog

**Project Description**
Tindog - a tinder for dogs

Stack:
[✔️ ] Html
[ ✔️] CSS
[ ✔️] Bootstrap

**Comment by gunjan-g** [comment]
@harshita2216 please assign the issue to me

**Comment by harshita2216** [comment]
> /assign

This isn't here! 😂 And I kind of like it this way only.

**Comment by gunjan-g** [comment]
> > /assign
> 
> This isn't here! 😂 And I kind of like it this way only.

Yes, I saw that and this makes the task so easy to assign yourself, but then I have to ping you for the label 😂
