### ISSUE TITLE
Adding image in breaking bad characters project

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#216]
### Due to some reason, images are not showing. I want to resolve this issue.
![bb](https://user-images.githubusercontent.com/72425181/125718007-6f50985a-13d9-471e-aa18-f323cc65289e.png)

**Comment by chicken-biryani** [comment]
@RiyaGupta89 Which project?

**Comment by RiyaGupta89** [comment]
@chicken-biryani  "breaking-bad-characters/"
