### ISSUE TITLE
Add Dark Mode feature to already existing project.

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#223]
Instructions :

1) Take an already existing project
2) Add a toggle button.
3) On clicking the toggle button the website should switch between dark mode and Light mode.

To make a PR:

1) Put the link of the project on which you want to add dark mode to in the comment of this issue.
2) Let someone assign it to you.
3) Clone
4) Create a seperate folder with the name: darkmode_<project name> example: darkmode_alarmclock
5) Copy the project in that folder, do the changes.
6) Add dark mode screenshot in the README
7) Create a PR.

Note:
All projects will be under level 03

**Comment by ayushseth07** [comment]
please assign this issue to me

**Comment by chicken-biryani** [comment]
@ayushseth07 Kindly, tell me for which project would you like to add a Dark mode along with the Project's link.

**Comment by ayushseth07** [comment]
@chicken-biryani i want to add darkmode to https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/todolist this project

**Comment by chicken-biryani** [comment]
Go ahead @ayushseth07

**Comment by chicken-biryani** [comment]
Go ahead @ayushseth07

**Comment by monishamandal02** [comment]
I want to add dark mode Can you please assign me for this: https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/Blog%20Application
