### ISSUE TITLE
Maths quiz game

### ISSUE THREAD

**Issue by nisha331** [Ayushparikh-code/Web-dev-mini-projects#231]
**Project title**
Maths quiz game

**Project Description**
This would give alert if the your addition is correct and if its wrong it would give correct ans and say to try again.
Stack:
Html
CSS
JavaScript

**Comment by nisha331** [comment]
I would like to work on the issue as a LGMSOC participant kindly assign it to me.

**Comment by harshita2216** [comment]
@nisha331 updates?

**Comment by nisha331** [comment]
Yes @harshita2216 on it .. Will submit the PR by tommorow.
