### ISSUE TITLE
Adding another quiz app

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#25]
Can I add another small quiz app project?

**Comment by Ayushparikh-code** [comment]
> Can I add another small quiz app project?

yes

**Comment by RiyaGupta89** [comment]
@There's some conflict with the files right now as soon you merged my cat-generate pr, I will raise this PR too.

**Comment by Ayushparikh-code** [comment]
> @there's some conflict with the files right now as soon you merged my cat-generate pr, I will raise this PR too.

Just do git pull command to fetch upstream ,that will solve ur conflicts

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code  git pull command is now working, can you HELP?
