### ISSUE TITLE
counter App

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#251]
**Project title**
Counter App

**Project Description**
a react counter app

Stack:
[ ] Html
[ ] CSS
[ ] JavaScript

**Comment by jugeshraghav** [comment]
i want to work on this issue

**Comment by harshita2216** [comment]
Check comment on #252

**Comment by jugeshraghav** [comment]
I have completed all the issues and closed one to reduce duplicacy. please assign this issue to me @harshita2216
