### ISSUE TITLE
Architecture Website Template

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#252]
**Project title**
Architecture Website Template

**Project Description**
a simple and responsive architecture website template.

Stack:
[ ] Html
[ ] CSS
[ ] JavaScript

**Comment by jugeshraghav** [comment]
i want to work on this issue

**Comment by harshita2216** [comment]
@jugeshraghav, you already have one open issue with inactivity for a long time. Please work on #139 first. We will assign this to you later.

**Comment by jugeshraghav** [comment]
I have completed all other issues and closed one to reduce duplicacy.  please assign it to me @harshita2216

**Comment by jugeshraghav** [comment]
I have completed all the issues please assign it to me now . @harshita2216
