### ISSUE TITLE
News App using React

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#262]
**News App**

* I want to add news app in the repository. I will use news api in the project that will fetch the most recent news and display it on the DOM.*

Stack:
[✔️] Html
[✔️] CSS
[✔️] JavaScript
[✔️]React

## How the project will look like: 
![news](https://user-images.githubusercontent.com/72425181/126251725-f93f6707-0ee7-4745-a6a8-8929a7def8e1.png)

**Comment by harshita2216** [comment]
@RiyaGupta89 updates?

**Comment by RiyaGupta89** [comment]
Yes, my code is ready. I will push it tomorrow morning. @harshita2216
