### ISSUE TITLE
Amazon Prime video login page clone

### ISSUE THREAD

**Issue by yellowberard** [Ayushparikh-code/Web-dev-mini-projects#277]
**Project title**
Amazon Prime video login page clone

**Project Description**
I have made a clone of login page clone of amazon prime video.
I have used only HTML and CSS
Stack:
[x] Html
[x] CSS
[ ] JavaScript

**Comment by yellowberard** [comment]
Please assign me this issue under LGM-SOC'21.

**Comment by harshita2216** [comment]
@yellowberard updates?

**Comment by yellowberard** [comment]
Ma'am my laptop crashed so I am not able to generate PR. I a have completed my code.

**Comment by harshita2216** [comment]
No problem @yellowberard. :) 
Just let me know if I need to close this or you would do it after you get your laptop fixed?

**Comment by yellowberard** [comment]
I will do it as soon as my laptop is fixed.

**Comment by harshita2216** [comment]
Okay. I'm closing this for now though. Will reopen once your laptop is fixed. Okay?

**Comment by yellowberard** [comment]
Okay, ma'am

**Comment by yellowberard** [comment]
@harshita2216  I have got my laptop back can you please reopen this issue.

**Comment by harshita2216** [comment]
Sure! Go ahead 🚀

**Comment by yellowberard** [comment]
@harshita2216 Ma'am no level is given to this issue, can you please give it.

**Comment by harshita2216** [comment]
> @harshita2216 Ma'am no level is given to this issue, can you please give it.

None of the issues have. Only PRs have labels. 
If you want to know more about the levels, kindly check readme of this repository.

**Comment by yellowberard** [comment]
Ok Ma'am
