### ISSUE TITLE
BMI Calculator using JS

### ISSUE THREAD

**Issue by supzi-del** [Ayushparikh-code/Web-dev-mini-projects#278]
**Project title**
BMI Calculator using JS

**Project Description**
The user enters height in cm and weight in kg in the input field to obtain their BMI

Stack:
[x] Html
[x] CSS
[x] JavaScript

**Comment by supzi-del** [comment]
Please assign it to me!

**Comment by harshita2216** [comment]
Hey, we already have 2 BMI Calculator projects. Make sure yours is different from theirs in terms of tech stack and UI. @supzi-del

**Comment by supzi-del** [comment]
> Hey, we already have 2 BMI Calculator projects. Make sure yours is different from theirs in terms of tech stack and UI. @supzi-del

I think in the other project, Flask is used and I will be using JavaScript. I will make PR if it's okay

**Comment by supzi-del** [comment]
I think one of the JS projects is pretty much the same. This would be duplicated so maybe you can close this

**Comment by harshita2216** [comment]
> I think one of the JS projects is pretty much the same. This would be duplicated so maybe you can close this

Just make changes to the UI of your project or add some more features.
