### ISSUE TITLE
Cat Generator Project

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#28]
Can I add this simple project where if a user click on the generate cat button, gifs gets added to the page? A user will learn managing click event from this project.
![catgenerator](https://user-images.githubusercontent.com/72425181/124349848-ff8cc300-dc0e-11eb-92c7-729a5582bb32.png)

**Comment by Ayushparikh-code** [comment]
> Can I add this simple project where if a user click on the generate cat button, gifs gets added to the page? A user will learn managing click event from this project.
> ![catgenerator](https://user-images.githubusercontent.com/72425181/124349848-ff8cc300-dc0e-11eb-92c7-729a5582bb32.png)

yeah sure ✌️
