### ISSUE TITLE
Add missing project details to index.md

### ISSUE THREAD

**Issue by harshita2216** [Ayushparikh-code/Web-dev-mini-projects#280]

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by Atif0604** [comment]
hey @harshita2216 can i work ?

**Comment by Atif0604** [comment]
hey @harshita2216 @chicken-biryani can i work as it has been 11 days since the issue is not resolved

**Comment by harshita2216** [comment]
> hey @harshita2216 @chicken-biryani can i work as it has been 11 days since the issue is not resolved

This issue would be closed as someone is already working on the index.md. 
I will reopen and assign it to you if we need this anytime soon.
