### ISSUE TITLE
clock/Stopwatch

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#3]

**Comment by Baba-Yaga-1** [comment]
Can I work on this issue under LGMSOC'21?

**Comment by Ayushparikh-code** [comment]
> Can I work on this issue under LGMSOC'21?

sure

**Comment by Ayushparikh-code** [comment]
> Can I work on this issue under LGMSOC'21?

Also add a README file to your project which consists the short description/screenshots about your project !

**Comment by Baba-Yaga-1** [comment]
Yeah sure.
