### ISSUE TITLE
Fix index.md

### ISSUE THREAD

**Issue by harshita2216** [Ayushparikh-code/Web-dev-mini-projects#306]
![image](https://user-images.githubusercontent.com/65803563/127007395-0e25b2ac-dd1c-4e52-8de7-9f6e097c146a.png)

Everybody is blindly copying the previous link and putting it up for their project. The correct way to add the link is - 

https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/Art-Gallery
The link should be Ayush's and not yours. If anybody is willing to work on this issue, kindly comment down below. 

There could be similar or other issues, kindly fix those as well.

**Comment by nisha331** [comment]
I would like to work on it kindly assign it to me. Even I have the same mistake for my previous PRs.
