### ISSUE TITLE
 add a Countdown Timer 

### ISSUE THREAD

**Issue by vanshika230** [Ayushparikh-code/Web-dev-mini-projects#31]
![Screenshot 2021-07-03 152348](https://user-images.githubusercontent.com/74042272/124350538-d9692200-dc12-11eb-8ea9-e8c5ff475ab4.jpg)

**Comment by vanshika230** [comment]
Can I add a Countdown Timer to repo under LGM-SoC?

**Comment by Ayushparikh-code** [comment]
> Can I add a Countdown Timer to repo under LGM-SoC?

Ok nice add it 👍🏻
