### ISSUE TITLE
adding images in readme 

### ISSUE THREAD

**Issue by ayushseth07** [Ayushparikh-code/Web-dev-mini-projects#313]
**Project name**
adding images in readme of all the projects wherever images are missing

**Comment by harshita2216** [comment]
I was thinking of creating an issue for fixing all such projects having no images. Would you like to do it for all the projects? It would be a Level 3 issue. @ayushseth07

**Comment by ayushseth07** [comment]
> I was thinking of creating an issue for fixing all such projects having no images. Would you like to do it for all the projects? It would be a Level 3 issue. @ayushseth07

ya sure , why not

**Comment by harshita2216** [comment]
> > I was thinking of creating an issue for fixing all such projects having no images. Would you like to do it for all the projects? It would be a Level 3 issue. @ayushseth07
> 
> ya sure , why not

Cool, please rename this issue.
