### ISSUE TITLE
Love Calculate App

### ISSUE THREAD

**Issue by RiyaGupta89** [Ayushparikh-code/Web-dev-mini-projects#32]
Can I add this love calculator app in the project?
![love-calculator](https://user-images.githubusercontent.com/72425181/124350844-8ee8a500-dc14-11eb-8339-976d388a34a9.png)

**Comment by Ayushparikh-code** [comment]
> Can I add this love calculator app in the project?
> ![love-calculator](https://user-images.githubusercontent.com/72425181/124350844-8ee8a500-dc14-11eb-8339-976d388a34a9.png)

Ok

**Comment by Ayushparikh-code** [comment]
> Can I add this love calculator app in the project?
> ![love-calculator](https://user-images.githubusercontent.com/72425181/124350844-8ee8a500-dc14-11eb-8339-976d388a34a9.png)

Also add this screenshot in a readme file inside your project folder and tell a bit about it also !
do this in all your other projects also ! 
becasue its easier for the visitors to understand project !
