### ISSUE TITLE
Javascript form validation

### ISSUE THREAD

**Issue by siddhi-244** [Ayushparikh-code/Web-dev-mini-projects#35]
I would like to add js form validation under lgmsoc

**Comment by Ayushparikh-code** [comment]
> I would like to add js form validation under lgmsoc

Ok sure

**Comment by Ayushparikh-code** [comment]
> I would like to add js form validation under lgmsoc

 Also add a README file to your project which consists the short description/screenshots about your project !

**Comment by siddhi-244** [comment]
Sure Sir !
