### ISSUE TITLE
Add a love calculator using random no generator

### ISSUE THREAD

**Issue by jugeshraghav** [Ayushparikh-code/Web-dev-mini-projects#366]
**Project title**
(Write project title over here)

**Project Description**
(Describe the project over here)

Stack:
[ ] Html
[ ] CSS
[ ] JavaScript

**Comment by jugeshraghav** [comment]
i would like to work on this issue.

**Comment by harshita2216** [comment]
Hey @jugeshraghav. LGMSoC is officially over hence this issue would not be considered for the leaderboard anymore. If you still want to work on this issue, you're free to do so.
