### ISSUE TITLE
Quote Generator

### ISSUE THREAD

**Issue by khushi-purwar** [Ayushparikh-code/Web-dev-mini-projects#37]
Can I add a quote generator project? Whenever a  user click on the button, he gets a new quote.

**Comment by Ayushparikh-code** [comment]
> Can I add a quote generator project? Whenever a user click on the button, he gets a new quote.

SURE

**Comment by Ayushparikh-code** [comment]
> Can I add a quote generator project? Whenever a user clicks on the button, he gets a new quote.

Also, add a README file to your project which consists of a short description/screenshots about your project!

**Comment by khushi-purwar** [comment]
Ok.

**Comment by khushi-purwar** [comment]
> > Can I add a quote generator project? Whenever a user clicks on the button, he gets a new quote.
> 
> Also, add a README file to your project which consists of a short description/screenshots about your project!

Ok.
