### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#4]

**Comment by Baba-Yaga-1** [comment]
Hey, Can I work on this issue ?

**Comment by Rounak-chauhan** [comment]
@Ayushparikh-code  sir i already make a pull request for this code please check it #9

**Comment by Ayushparikh-code** [comment]
> @Ayushparikh-code sir i already make a pull request for this code please check it #9

ok will check it

**Comment by Ayushparikh-code** [comment]
> Hey, Can I work on this issue under LGMSOC'21?

sorry I assigned rounak for this issue so head over to other issues or create your own issue to add ur project !

**Comment by Rounak-chauhan** [comment]
@Ayushparikh-code  sir please recheck again i had made another pull request for that #12
