### ISSUE TITLE
Flask news app

### ISSUE THREAD

**Issue by drashtipatel2503** [Ayushparikh-code/Web-dev-mini-projects#43]
A mini news app which shows most recent news headlines,  and content which includes news related to sports, entertainment, crypto-currencies, business, science, technology and others

**Comment by Ayushparikh-code** [comment]
> A mini news app which shows most recent news headlines, and content which includes news related to sports, entertainment, crypto-currencies, business, science, technology and others

ok assigned u for this project ✔️✌️
