### ISSUE TITLE
Score Keeper

### ISSUE THREAD

**Issue by yellowberard** [Ayushparikh-code/Web-dev-mini-projects#49]
I would like to add a score keeper project where user can keep the account of there score in ping pom game where user can select max points and as soon as one of the two player reaches max points color changes . I have made this using HTML,CSS & JS.
It is almost finished. So, please assign me the issue.

Please assign me this issue under LGMSOC'21

**Comment by yellowberard** [comment]
@Ayushparikh-code  I also wanted to ask can we update our projects once a PR is accepted.

**Comment by Ayushparikh-code** [comment]
> I would like to add a score keeper project where user can keep the account of there score in ping pom game where user can select max points and as soon as one of the two player reaches max points color changes . I have made this using HTML,CSS & JS.
> It is almost finished. So, please assign me the issue.
> 
> Please assign me this issue under LGMSOC'21

done

**Comment by Ayushparikh-code** [comment]
> @Ayushparikh-code I also wanted to ask can we update our projects once a PR is accepted.

yes, u can update your project but have to create a new PR for your changes done!

**Comment by yellowberard** [comment]
Ok Sir, Thank You
