### ISSUE TITLE
Google.com page

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#5]
make clone of https://www.google.com/ page

**Comment by RiyaGupta89** [comment]
Can I work on this issue please?

**Comment by Ayushparikh-code** [comment]
> Can I work on this issue please?

sure

**Comment by RiyaGupta89** [comment]
Please assign me, I have completed my other two issues :)

**Comment by Ayushparikh-code** [comment]
> Please assign me, I have completed my other two issues :)

assigned u for this issue ✔️👍
