### ISSUE TITLE
To make corrections in external Linking of of CSS and JavaScript in To-Do -List Project

### ISSUE THREAD

**Issue by puneetkaur2929** [Ayushparikh-code/Web-dev-mini-projects#51]
Hey @Ayushparikh-code 
As you can see there is error in linking of css and javascript in case of TO-DO-List Project due to which it is not working properly.
I am interested to work on this issue under LGM SOC '21 .
Kindly assign this issue to me.

**Comment by Ayushparikh-code** [comment]
> Hey @Ayushparikh-code
> As you can see there is error in linking of css and javascript in case of TO-DO-List Project due to which it is not working properly.
> I am interested to work on this issue under LGM SOC '21 .
> Kindly assign this issue to me.

yeah
