### ISSUE TITLE
Add Readme.md file to To - Do list webapp.

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#53]
Add a small README.md file to the To -Do project.

Contents of the README:

- Project overview.
- Use of the project.
- Stack of your project.
- How to set up / run your project.
- Screenshots of the pages / output.
(A short description under each screenshot... Describing the page a little bit)

This would help visitors / developers in genral.

**Comment by Atif0604** [comment]
@chicken-biryani can i do it

**Comment by chicken-biryani** [comment]
@Atif0604 Yes go ahead!
