### ISSUE TITLE
Add Readme.md to Random Color Generator

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#55]
Add a small README.md file to the Random Color Generator

Contents of the README:

-Project overview.
-Use of the project.
-Stack of your project.
-How to set up / run your project.
-Screenshots of the pages/output.
(A short description under each screenshot... Describing the page a little bit)
This would help visitors/developers in general.

**Comment by yellowberard** [comment]
Please assign me this issue under LGMSOC'21
