### ISSUE TITLE
Fix dropdown menu in the navbar

### ISSUE THREAD

**Issue by AnvitaPrasad** [Ayushparikh-code/Web-dev-mini-projects#568]
**Project name**
Band Website

**Project link**
https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/Band%20Website

**Improvements suggested**
The 'More' dropdown in the navbar reloads the page instead of showing the dropdown content. This issue needs to be fixed so that clicking 'More' displays the dropdown menu without reloading the page

**Comment by vdhanakotti-15102004** [comment]
I  take the project

**Comment by N0tMikE04** [comment]
@AnvitaPrasad i would like to help you in your issue
