### ISSUE TITLE
Find me A dog

### ISSUE THREAD

**Issue by kycilius** [Ayushparikh-code/Web-dev-mini-projects#576]
**Project title**
what dog i should get?

**Project Description**
i have made website which will help you decide which dog breed you should prefer by judging:
(i)  your location
(ii) your house space
(iii) how much you are free
(iv) your personality

Stack:
[x] Html
[x] CSS
[x] JavaScript

**plz assing me this under hacktoberfeast'24 **

**Comment by sanjevraj-J** [comment]
i will take this project
