### ISSUE TITLE
Minimalistic  Project : Qr code Generator  On the Given String

### ISSUE THREAD

**Issue by raj-mistry-01** [Ayushparikh-code/Web-dev-mini-projects#581]
I hope you will assign this issue to me , As I will push this mini web project to this repo and look further contribution to this repo.

**Comment by sanjevraj-J** [comment]
i take this projects

**Comment by vishnuvardhancoder** [comment]
Hi,let me work on this one.

**Comment by PranikaBaby** [comment]
i will solve it
