### ISSUE TITLE
BUILD A JAVASCRIPT GAME

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#6]

**Comment by Ciggzy1312** [comment]
I can work on this issue
I can make a rock paper scissor game

**Comment by RiyaGupta89** [comment]
I can work on this too. I can add dinosaur game. And falling ball game. Please assign me this issue.

**Comment by Ayushparikh-code** [comment]
> I can work on this too. I can add dinosaur game. And falling ball game. Please assign me this issue.

ok
