### ISSUE TITLE
Add Readme to Web-dev-mini-projects/.vscode/

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#61]
Add a small README.md file to the project.

Contents of the README:

-Project overview.
-Use of the project.
-Stack of your project.
-How to set up / run your project.
-Screenshots of the pages/output.
(A short description under each screenshot... Describing the page a little bit)
This would help visitors/developers in general.

**Comment by khushi-purwar** [comment]
> Add a small README.md file to the project.
> 
> Contents of the README:
> 
> -Project overview.
> -Use of the project.
> -Stack of your project.
> -How to set up / run your project.
> -Screenshots of the pages/output.
> (A short description under each screenshot... Describing the page a little bit)
> This would help visitors/developers in general.

Can i work on this issue @chicken-biryani

**Comment by chicken-biryani** [comment]
Yess

**Comment by Ayushparikh-code** [comment]
> > Add a small README.md file to the project.
> > Contents of the README:
> > -Project overview.
> > -Use of the project.
> > -Stack of your project.
> > -How to set up / run your project.
> > -Screenshots of the pages/output.
> > (A short description under each screenshot... Describing the page a little bit)
> > This would help visitors/developers in general.
> 
> Can i work on this issue @chicken-biryani

**Comment by Ayushparikh-code** [comment]
Closing this issue because it's not a project so no need to add readme to it

**Comment by Ayushparikh-code** [comment]
> Sorry for inconvenience but am Closing this issue because it's not a project so no need to add readme to it
