### ISSUE TITLE
Add README.md file to Basic Background Generator

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#62]
Add a small README.md file to the project.

Contents of the README:

-Project overview.
-Use of the project.
-Stack of your project.
-How to set up / run your project.
-Screenshots of the pages/output.
(A short description under each screenshot... Describing the page a little bit)
This would help visitors/developers in general.

**Comment by Atif0604** [comment]
can i work on this

**Comment by mrkc2303** [comment]
It's my project, I can do it. Please assign me @chicken-biryani

**Comment by chicken-biryani** [comment]
@Atif0604 let @mrkc2303 do it. You can do the rest.
