### ISSUE TITLE
Add README.md file to CALCULATOR

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#63]
Add a small README.md file to the project.

Contents of the README:

-Project overview.
-Use of the project.
-Stack of your project.
-How to set up / run your project.
-Screenshots of the pages/output.
(A short description under each screenshot... Describing the page a little bit)
This would help visitors/developers in general.

**Comment by Atif0604** [comment]
can i work on this
