### ISSUE TITLE
BUILD A QUIZ APP

### ISSUE THREAD

**Issue by Ayushparikh-code** [Ayushparikh-code/Web-dev-mini-projects#7]

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code Can I work on this issue please?

**Comment by Ayushparikh-code** [comment]
> @Ayushparikh-code Can I work on this issue please?

ok

**Comment by arnav1776** [comment]
I would like to work on this issue

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code  Please assign me, I have completed my other two issues :)

**Comment by Ayushparikh-code** [comment]
> I would like to work on this issue

assigned u for this ✔️👍

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code But I though you'll assign me the issue. You have said okay, when I asked you to assign me the issue. I've finished building this project too.

**Comment by Ayushparikh-code** [comment]
> @Ayushparikh-code But I though you'll assign me the issue. You have said okay, when I asked you to assign me the issue. I've finished building this project too.

ok no problem u can build it by creating a separate issue for that because this issue is already to @arnav1776 hence merging pr closed this issue !
