### ISSUE TITLE
adding a drum kit 

### ISSUE THREAD

**Issue by ayushseth07** [Ayushparikh-code/Web-dev-mini-projects#73]

**Comment by ayushseth07** [comment]
can i work on this issue

**Comment by Ayushparikh-code** [comment]
> can i work on this issue

Yeah

**Comment by harshita2216** [comment]
@Ayushparikh-code, someone has already created this and it's merged.

**Comment by Ayushparikh-code** [comment]
> @Ayushparikh-code, someone has already created this and it's merged.

it is ok, allow @ayushseth07  to make this Drumkit project if he wants to make a different drumkit than the previous one merged! we can keep both projects in our repo!
