### ISSUE TITLE
Add Mantainers section to Readme

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#75]
The Readme doesn't have a mantainers section.

To do:

Add maintainer's section After "Our valuable Contributors".
And should contain @chicken-biryani 's and @Ayushparikh-code 's profile.

Use :

https://github.com/HarshCasper/Rotten-Scripts/blob/master/MAINTAINERS.md

for reference.

**Comment by Atif0604** [comment]
Can i go for it?
