### ISSUE TITLE
Basic Portfolio Website 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Ayushparikh-code/Web-dev-mini-projects#8]
Hey @Ayushparikh-code sir during my HTML and CSS learning days I made a basic portfolio website would love to add that as a project by making few upgrades using HTML and CSS. Can I work on it ? 
@Ayushparikh-code sir Please assign this issue to me as I am LGM-SOC'21 participant

**Comment by Ayushparikh-code** [comment]
> Hey @Ayushparikh-code sir during my HTML and CSS learning days I made a basic portfolio website would love to add that as a project by making few upgrades using HTML and CSS. Can I work on it ?
> @Ayushparikh-code sir Please assign this issue to me as I am LGM-SOC'21 participant

ok assigned you , now start working on it !
