### ISSUE TITLE
Create index.md

### ISSUE THREAD

**Issue by chicken-biryani** [Ayushparikh-code/Web-dev-mini-projects#91]
Index.md should have :
A table that consists of : 

1) Name of project [In the form of link] - Use https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/README.md for reference
2) Short description of the project.

For ALL the projects

Example:

| Name                                          | Description                        |
|------------------------------------|------------------------------|
|[To - DO list](https://github.com/Ayushparikh-code/Web-dev-mini-projects/tree/main/To-Do%20List)          | To-Do List                          |

**Comment by Atif0604** [comment]
can i work on this?

**Comment by harshita2216** [comment]
@Atif0604, go ahead!
